[tool.poetry]
name = "projeto-pratico"
version = "0.1.0"
description = ""
authors = ["Luciano"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.14"
streamlit = ">=1.53.1,<2.0.0"
pandas = "<3.0.0"


